### ISSUE TITLE
One module github.com/bseolized/shadowmaker seems invalid

### ISSUE THREAD

**Issue by kortov** [triamazikamno/tinkoff-invest#1]
The [repo](https://github.com/bseolized/shadowmaker) is missing, the module is not resolved 

https://github.com/triamazikamno/tinkoff-invest/blob/d99fdef6b3c0174bb78789e3730b8c911aa113bd/go.mod#L9

https://github.com/triamazikamno/tinkoff-invest/blob/d99fdef6b3c0174bb78789e3730b8c911aa113bd/internal/bot/info.go#L243

**Comment by triamazikamno** [comment]
Спасибо, поправил

**Comment by kortov** [comment]
Спасибо, я новичок в go, но я думаю эту строку тоже нужно удалить? 
https://github.com/triamazikamno/tinkoff-invest/blob/e6dfcee432a739d191edb3f327e58a1d5f8652b5/go.mod#L9

**Comment by triamazikamno** [comment]
Точно, спасибо :) Проверил билд на сторонней машине, все работает теперь.
